export type Theater =
  | "Western Europe"
  | "Eastern Front"
  | "North Africa"
  | "Mediterranean"
  | "Pacific"
  | "Asia"
  | "Atlantic"
  | "Scandinavia";

export interface Battle {
  code: string;
  latitude: number;
  longitude: number;
  name: string;
  year: number;
  theater: Theater;
}

export const battles: Battle[] = [
  // --- Eastern Front ---
  {
    code: "stalingrad",
    latitude: 48.71,
    longitude: 44.51,
    name: "Stalingrad",
    year: 1942,
    theater: "Eastern Front",
  },
  {
    code: "kursk",
    latitude: 51.5,
    longitude: 36.2,
    name: "Kursk",
    year: 1943,
    theater: "Eastern Front",
  },
  {
    code: "moscow",
    latitude: 55.75,
    longitude: 37.62,
    name: "Moscow",
    year: 1941,
    theater: "Eastern Front",
  },
  {
    code: "leningrad",
    latitude: 59.94,
    longitude: 30.31,
    name: "Leningrad",
    year: 1941,
    theater: "Eastern Front",
  },
  {
    code: "kiev-1941",
    latitude: 50.45,
    longitude: 30.52,
    name: "Kiev",
    year: 1941,
    theater: "Eastern Front",
  },
  {
    code: "smolensk",
    latitude: 54.78,
    longitude: 32.05,
    name: "Smolensk",
    year: 1941,
    theater: "Eastern Front",
  },
  {
    code: "kharkov",
    latitude: 49.99,
    longitude: 36.23,
    name: "Kharkov",
    year: 1943,
    theater: "Eastern Front",
  },
  {
    code: "sevastopol",
    latitude: 44.6,
    longitude: 33.52,
    name: "Sevastopol",
    year: 1942,
    theater: "Eastern Front",
  },
  {
    code: "brest-fortress",
    latitude: 52.08,
    longitude: 23.66,
    name: "Brest Fortress",
    year: 1941,
    theater: "Eastern Front",
  },
  {
    code: "minsk-1944",
    latitude: 53.9,
    longitude: 27.57,
    name: "Minsk (Operation Bagration)",
    year: 1944,
    theater: "Eastern Front",
  },
  {
    code: "rzhev",
    latitude: 56.26,
    longitude: 34.33,
    name: "Rzhev",
    year: 1942,
    theater: "Eastern Front",
  },
  {
    code: "demyansk",
    latitude: 57.64,
    longitude: 32.28,
    name: "Demyansk Pocket",
    year: 1942,
    theater: "Eastern Front",
  },
  {
    code: "kerch",
    latitude: 45.36,
    longitude: 36.47,
    name: "Kerch Peninsula",
    year: 1942,
    theater: "Eastern Front",
  },
  {
    code: "korsun-pocket",
    latitude: 49.42,
    longitude: 31.26,
    name: "Korsun Pocket",
    year: 1944,
    theater: "Eastern Front",
  },
  {
    code: "narva",
    latitude: 59.38,
    longitude: 28.19,
    name: "Narva",
    year: 1944,
    theater: "Eastern Front",
  },
  {
    code: "rostov",
    latitude: 47.24,
    longitude: 39.71,
    name: "Rostov",
    year: 1941,
    theater: "Eastern Front",
  },
  {
    code: "debrecen",
    latitude: 47.53,
    longitude: 21.64,
    name: "Debrecen",
    year: 1944,
    theater: "Eastern Front",
  },
  {
    code: "budapest",
    latitude: 47.5,
    longitude: 19.04,
    name: "Budapest",
    year: 1945,
    theater: "Eastern Front",
  },
  {
    code: "vienna-offensive",
    latitude: 48.21,
    longitude: 16.37,
    name: "Vienna Offensive",
    year: 1945,
    theater: "Eastern Front",
  },
  {
    code: "berlin",
    latitude: 52.52,
    longitude: 13.4,
    name: "Berlin",
    year: 1945,
    theater: "Eastern Front",
  },
  {
    code: "seelow-heights",
    latitude: 52.53,
    longitude: 14.38,
    name: "Seelow Heights",
    year: 1945,
    theater: "Eastern Front",
  },
  {
    code: "koenigsberg",
    latitude: 54.71,
    longitude: 20.51,
    name: "Königsberg",
    year: 1945,
    theater: "Eastern Front",
  },
  {
    code: "warsaw-uprising",
    latitude: 52.23,
    longitude: 21.01,
    name: "Warsaw Uprising",
    year: 1944,
    theater: "Eastern Front",
  },
  {
    code: "lvov",
    latitude: 49.84,
    longitude: 24.03,
    name: "Lvov (Lvov-Sandomierz Offensive)",
    year: 1944,
    theater: "Eastern Front",
  },
  {
    code: "jassy-kishinev",
    latitude: 47.01,
    longitude: 28.86,
    name: "Jassy-Kishinev Offensive",
    year: 1944,
    theater: "Eastern Front",
  },
  {
    code: "odessa",
    latitude: 46.48,
    longitude: 30.73,
    name: "Odessa",
    year: 1941,
    theater: "Eastern Front",
  },
  {
    code: "caucasus",
    latitude: 43.02,
    longitude: 44.68,
    name: "Caucasus",
    year: 1942,
    theater: "Eastern Front",
  },
  {
    code: "novorossiysk",
    latitude: 44.72,
    longitude: 37.77,
    name: "Novorossiysk",
    year: 1943,
    theater: "Eastern Front",
  },
  {
    code: "dnieper",
    latitude: 48.46,
    longitude: 34.0,
    name: "Dnieper",
    year: 1943,
    theater: "Eastern Front",
  },
  {
    code: "westerplatte",
    latitude: 54.41,
    longitude: 18.67,
    name: "Westerplatte",
    year: 1939,
    theater: "Eastern Front",
  },
  {
    code: "bzura",
    latitude: 52.2,
    longitude: 19.72,
    name: "Bzura",
    year: 1939,
    theater: "Eastern Front",
  },
  // --- Scandinavia ---
  {
    code: "narvik",
    latitude: 68.44,
    longitude: 17.43,
    name: "Narvik",
    year: 1940,
    theater: "Scandinavia",
  },
  {
    code: "drobak-sound",
    latitude: 59.67,
    longitude: 10.6,
    name: "Drøbak Sound",
    year: 1940,
    theater: "Scandinavia",
  },
  {
    code: "suomussalmi",
    latitude: 64.88,
    longitude: 28.92,
    name: "Suomussalmi",
    year: 1939,
    theater: "Scandinavia",
  },
  {
    code: "tali-ihantala",
    latitude: 60.84,
    longitude: 28.92,
    name: "Tali-Ihantala",
    year: 1944,
    theater: "Scandinavia",
  },
  {
    code: "petsamo-kirkenes",
    latitude: 69.55,
    longitude: 30.85,
    name: "Petsamo-Kirkenes Offensive",
    year: 1944,
    theater: "Scandinavia",
  },
  // --- Pacific ---
  {
    code: "pearl-harbor",
    latitude: 21.36,
    longitude: -157.95,
    name: "Pearl Harbor",
    year: 1941,
    theater: "Pacific",
  },
  {
    code: "midway",
    latitude: 28.2,
    longitude: -177.35,
    name: "Midway",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "coral-sea",
    latitude: -15.5,
    longitude: 155.5,
    name: "Coral Sea",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "guadalcanal",
    latitude: -9.43,
    longitude: 160.05,
    name: "Guadalcanal",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "iwo-jima",
    latitude: 24.78,
    longitude: 141.32,
    name: "Iwo Jima",
    year: 1945,
    theater: "Pacific",
  },
  {
    code: "okinawa",
    latitude: 26.33,
    longitude: 127.8,
    name: "Okinawa",
    year: 1945,
    theater: "Pacific",
  },
  {
    code: "leyte-gulf",
    latitude: 10.36,
    longitude: 125.4,
    name: "Leyte Gulf",
    year: 1944,
    theater: "Pacific",
  },
  {
    code: "philippine-sea",
    latitude: 15.0,
    longitude: 136.0,
    name: "Philippine Sea",
    year: 1944,
    theater: "Pacific",
  },
  {
    code: "tarawa",
    latitude: 1.42,
    longitude: 172.98,
    name: "Tarawa",
    year: 1943,
    theater: "Pacific",
  },
  {
    code: "peleliu",
    latitude: 7.0,
    longitude: 134.25,
    name: "Peleliu",
    year: 1944,
    theater: "Pacific",
  },
  {
    code: "saipan",
    latitude: 15.19,
    longitude: 145.75,
    name: "Saipan",
    year: 1944,
    theater: "Pacific",
  },
  {
    code: "guam",
    latitude: 13.44,
    longitude: 144.79,
    name: "Guam",
    year: 1944,
    theater: "Pacific",
  },
  {
    code: "wake-island",
    latitude: 19.28,
    longitude: 166.64,
    name: "Wake Island",
    year: 1941,
    theater: "Pacific",
  },
  {
    code: "bataan",
    latitude: 14.68,
    longitude: 120.5,
    name: "Bataan",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "manila",
    latitude: 14.6,
    longitude: 120.98,
    name: "Manila",
    year: 1945,
    theater: "Pacific",
  },
  {
    code: "milne-bay",
    latitude: -10.32,
    longitude: 150.46,
    name: "Milne Bay",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "kokoda-track",
    latitude: -9.1,
    longitude: 147.73,
    name: "Kokoda Track",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "buna-gona",
    latitude: -8.66,
    longitude: 148.38,
    name: "Buna-Gona",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "rabaul",
    latitude: -4.2,
    longitude: 152.17,
    name: "Rabaul",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "bougainville",
    latitude: -6.22,
    longitude: 155.2,
    name: "Bougainville",
    year: 1943,
    theater: "Pacific",
  },
  {
    code: "bismarck-sea",
    latitude: -7.25,
    longitude: 148.5,
    name: "Bismarck Sea",
    year: 1943,
    theater: "Pacific",
  },
  {
    code: "attu",
    latitude: 52.85,
    longitude: 173.18,
    name: "Attu",
    year: 1943,
    theater: "Pacific",
  },
  {
    code: "darwin",
    latitude: -12.46,
    longitude: 130.84,
    name: "Darwin Raid",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "java-sea",
    latitude: -5.9,
    longitude: 112.0,
    name: "Java Sea",
    year: 1942,
    theater: "Pacific",
  },
  {
    code: "eniwetok",
    latitude: 11.5,
    longitude: 162.33,
    name: "Eniwetok",
    year: 1944,
    theater: "Pacific",
  },
  {
    code: "kwajalein",
    latitude: 8.72,
    longitude: 167.73,
    name: "Kwajalein",
    year: 1944,
    theater: "Pacific",
  },
  // --- Western Europe ---
  {
    code: "normandy",
    latitude: 49.35,
    longitude: -0.6,
    name: "Normandy (D-Day)",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "dunkirk",
    latitude: 51.03,
    longitude: 2.37,
    name: "Dunkirk",
    year: 1940,
    theater: "Western Europe",
  },
  {
    code: "battle-of-britain",
    latitude: 51.1,
    longitude: 0.7,
    name: "Battle of Britain",
    year: 1940,
    theater: "Western Europe",
  },
  {
    code: "sedan",
    latitude: 49.7,
    longitude: 4.94,
    name: "Sedan",
    year: 1940,
    theater: "Western Europe",
  },
  {
    code: "eben-emael",
    latitude: 50.8,
    longitude: 5.68,
    name: "Eben-Emael",
    year: 1940,
    theater: "Western Europe",
  },
  {
    code: "dieppe",
    latitude: 49.92,
    longitude: 1.08,
    name: "Dieppe Raid",
    year: 1942,
    theater: "Western Europe",
  },
  {
    code: "st-nazaire",
    latitude: 47.28,
    longitude: -2.2,
    name: "St. Nazaire Raid",
    year: 1942,
    theater: "Western Europe",
  },
  {
    code: "falaise",
    latitude: 48.89,
    longitude: -0.19,
    name: "Falaise Pocket",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "arnhem",
    latitude: 51.98,
    longitude: 5.91,
    name: "Arnhem (Operation Market Garden)",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "hurtgen-forest",
    latitude: 50.7,
    longitude: 6.37,
    name: "Hürtgen Forest",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "aachen",
    latitude: 50.78,
    longitude: 6.08,
    name: "Aachen",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "bastogne",
    latitude: 50.0,
    longitude: 5.72,
    name: "Bastogne (Battle of the Bulge)",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "remagen",
    latitude: 50.58,
    longitude: 7.24,
    name: "Remagen",
    year: 1945,
    theater: "Western Europe",
  },
  {
    code: "operation-varsity",
    latitude: 51.66,
    longitude: 6.62,
    name: "Operation Varsity (Wesel)",
    year: 1945,
    theater: "Western Europe",
  },
  {
    code: "ruhr-pocket",
    latitude: 51.45,
    longitude: 7.3,
    name: "Ruhr Pocket",
    year: 1945,
    theater: "Western Europe",
  },
  {
    code: "paris",
    latitude: 48.86,
    longitude: 2.35,
    name: "Liberation of Paris",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "operation-dragoon",
    latitude: 43.25,
    longitude: 6.6,
    name: "Operation Dragoon",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "cherbourg",
    latitude: 49.64,
    longitude: -1.62,
    name: "Cherbourg",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "scheldt",
    latitude: 51.4,
    longitude: 3.8,
    name: "Scheldt",
    year: 1944,
    theater: "Western Europe",
  },
  {
    code: "metz",
    latitude: 49.12,
    longitude: 6.18,
    name: "Metz",
    year: 1944,
    theater: "Western Europe",
  },
  // --- North Africa ---
  {
    code: "el-alamein",
    latitude: 30.83,
    longitude: 28.95,
    name: "El Alamein",
    year: 1942,
    theater: "North Africa",
  },
  {
    code: "tobruk",
    latitude: 32.08,
    longitude: 23.96,
    name: "Tobruk",
    year: 1941,
    theater: "North Africa",
  },
  {
    code: "gazala",
    latitude: 32.15,
    longitude: 23.35,
    name: "Gazala",
    year: 1942,
    theater: "North Africa",
  },
  {
    code: "sidi-barrani",
    latitude: 31.61,
    longitude: 25.93,
    name: "Sidi Barrani",
    year: 1940,
    theater: "North Africa",
  },
  {
    code: "beda-fomm",
    latitude: 30.76,
    longitude: 20.18,
    name: "Beda Fomm",
    year: 1941,
    theater: "North Africa",
  },
  {
    code: "kasserine-pass",
    latitude: 35.17,
    longitude: 8.83,
    name: "Kasserine Pass",
    year: 1943,
    theater: "North Africa",
  },
  {
    code: "operation-torch",
    latitude: 36.75,
    longitude: 3.06,
    name: "Operation Torch",
    year: 1942,
    theater: "North Africa",
  },
  {
    code: "tunis",
    latitude: 36.81,
    longitude: 10.18,
    name: "Tunis",
    year: 1943,
    theater: "North Africa",
  },
  {
    code: "mareth-line",
    latitude: 33.63,
    longitude: 10.3,
    name: "Mareth Line",
    year: 1943,
    theater: "North Africa",
  },
  {
    code: "bir-hakeim",
    latitude: 31.59,
    longitude: 23.48,
    name: "Bir Hakeim",
    year: 1942,
    theater: "North Africa",
  },
  // --- Mediterranean ---
  {
    code: "taranto",
    latitude: 40.43,
    longitude: 17.25,
    name: "Taranto Raid",
    year: 1940,
    theater: "Mediterranean",
  },
  {
    code: "cape-matapan",
    latitude: 35.9,
    longitude: 21.2,
    name: "Cape Matapan",
    year: 1941,
    theater: "Mediterranean",
  },
  {
    code: "crete",
    latitude: 35.34,
    longitude: 25.13,
    name: "Crete",
    year: 1941,
    theater: "Mediterranean",
  },
  {
    code: "malta",
    latitude: 35.9,
    longitude: 14.45,
    name: "Siege of Malta",
    year: 1942,
    theater: "Mediterranean",
  },
  {
    code: "sicily",
    latitude: 37.08,
    longitude: 14.5,
    name: "Sicily (Operation Husky)",
    year: 1943,
    theater: "Mediterranean",
  },
  {
    code: "salerno",
    latitude: 40.55,
    longitude: 14.85,
    name: "Salerno",
    year: 1943,
    theater: "Mediterranean",
  },
  {
    code: "anzio",
    latitude: 41.45,
    longitude: 12.62,
    name: "Anzio",
    year: 1944,
    theater: "Mediterranean",
  },
  {
    code: "monte-cassino",
    latitude: 41.49,
    longitude: 13.81,
    name: "Monte Cassino",
    year: 1944,
    theater: "Mediterranean",
  },
  {
    code: "gothic-line",
    latitude: 44.0,
    longitude: 11.8,
    name: "Gothic Line",
    year: 1944,
    theater: "Mediterranean",
  },
  {
    code: "greece",
    latitude: 39.9,
    longitude: 22.4,
    name: "Battle of Greece",
    year: 1941,
    theater: "Mediterranean",
  },
  {
    code: "mers-el-kebir",
    latitude: 35.73,
    longitude: -0.68,
    name: "Mers-el-Kébir",
    year: 1940,
    theater: "Mediterranean",
  },
  // --- Asia ---
  {
    code: "kohima",
    latitude: 25.67,
    longitude: 94.1,
    name: "Kohima",
    year: 1944,
    theater: "Asia",
  },
  {
    code: "imphal",
    latitude: 24.82,
    longitude: 93.94,
    name: "Imphal",
    year: 1944,
    theater: "Asia",
  },
  {
    code: "singapore",
    latitude: 1.35,
    longitude: 103.82,
    name: "Singapore",
    year: 1942,
    theater: "Asia",
  },
  {
    code: "hong-kong",
    latitude: 22.32,
    longitude: 114.17,
    name: "Hong Kong",
    year: 1941,
    theater: "Asia",
  },
  {
    code: "slim-river",
    latitude: 3.83,
    longitude: 101.4,
    name: "Slim River",
    year: 1942,
    theater: "Asia",
  },
  {
    code: "changsha",
    latitude: 28.23,
    longitude: 112.94,
    name: "Changsha",
    year: 1941,
    theater: "Asia",
  },
  {
    code: "hengyang",
    latitude: 26.89,
    longitude: 112.61,
    name: "Hengyang",
    year: 1944,
    theater: "Asia",
  },
  {
    code: "kunlun-pass",
    latitude: 22.98,
    longitude: 108.72,
    name: "Kunlun Pass",
    year: 1939,
    theater: "Asia",
  },
  {
    code: "yenangyaung",
    latitude: 20.46,
    longitude: 94.87,
    name: "Yenangyaung",
    year: 1942,
    theater: "Asia",
  },
  {
    code: "meiktila",
    latitude: 20.88,
    longitude: 95.86,
    name: "Meiktila",
    year: 1945,
    theater: "Asia",
  },
  {
    code: "admin-box",
    latitude: 21.0,
    longitude: 92.4,
    name: "Admin Box",
    year: 1944,
    theater: "Asia",
  },
  {
    code: "khalkhin-gol",
    latitude: 47.72,
    longitude: 118.62,
    name: "Khalkhin Gol",
    year: 1939,
    theater: "Asia",
  },
  // --- Atlantic ---
  {
    code: "river-plate",
    latitude: -35.0,
    longitude: -55.65,
    name: "River Plate",
    year: 1939,
    theater: "Atlantic",
  },
  {
    code: "denmark-strait",
    latitude: 65.5,
    longitude: -28.0,
    name: "Denmark Strait",
    year: 1941,
    theater: "Atlantic",
  },
  {
    code: "north-cape",
    latitude: 72.5,
    longitude: 25.5,
    name: "North Cape",
    year: 1943,
    theater: "Atlantic",
  },
  {
    code: "barents-sea",
    latitude: 73.3,
    longitude: 30.0,
    name: "Barents Sea",
    year: 1942,
    theater: "Atlantic",
  },
  {
    code: "channel-dash",
    latitude: 50.5,
    longitude: 1.0,
    name: "Channel Dash",
    year: 1942,
    theater: "Atlantic",
  },
];

export const battleCodesWithImage = battles.map((battle) => battle.code);

export const battlesWithImage = battles.filter((battle) =>
  battleCodesWithImage.includes(battle.code)
);

export function getBattleName(language: string, battle: Battle) {
  // Battle names are shared across languages for now.
  return battle.name;
}

export function sanitizeBattleName(battleName: string): string {
  return battleName
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[- '()]/g, "")
    .toLowerCase();
}
